webtalk_init -webtalk_dir C:/Users/Paula/OneDrive - Universidad de Alcala/Todo/vivado/E1/FIFO_XADC/P1_fifo_xadc.sim/sim_1/behav/xsim/xsim.dir/prueba_xadc_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Nov 11 13:36:47 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8720db0f-e4af-4ff1-bce6-a7572e8b6308" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e06165ee33124632814c5567ac626386" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "71" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3400G with Radeon Vega Graphics    " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3700 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "402270855 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.30_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9124_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2400904658 -regid "" -xml C:/Users/Paula/OneDrive - Universidad de Alcala/Todo/vivado/E1/FIFO_XADC/P1_fifo_xadc.sim/sim_1/behav/xsim/xsim.dir/prueba_xadc_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Paula/OneDrive - Universidad de Alcala/Todo/vivado/E1/FIFO_XADC/P1_fifo_xadc.sim/sim_1/behav/xsim/xsim.dir/prueba_xadc_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Paula/OneDrive - Universidad de Alcala/Todo/vivado/E1/FIFO_XADC/P1_fifo_xadc.sim/sim_1/behav/xsim/xsim.dir/prueba_xadc_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
